config/routes.rb
Rails.application.routes.draw do
  resources :images, only: [:create, :destroy]
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :releases
  resources :artists
  resources :events
  resources :studio, only: [:index]
  resources :about, only: [:index]
  resources :contact, only: [:index]

  post 'contact', to: 'contact#new'

  root to: "home#index"
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_attached_file :photo,
                    :styles => { :home => "300x300", :thumb => "100x100" },
                    :s3_protocol => 'https',
                    :s3_host_name => ENV['S3_HOST_NAME'],
                    :path => ENV['S3_PATH_ARTISTS'],
                    :storage => 's3',
                    :s3_region => ENV['AWS_REGION'],
                    :bucket => ENV['S3_BUCKET_NAME']

  #TODO set default "missing" image to loudhouse logo

  has_many :releases, dependent: :destroy

  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all.sort_by(&:name)
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_artist
    @artist = Artist.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def artist_params
    params.require(:artist).permit(:name, :description, :photo, :featured)
  end
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "description" %>
  </div>

  <div class="field">
    <%= form.label :photo, "Photo" %>
    <%= form.file_field :photo %>
  </div>

  <div class="field>">
    <%= form.label :featured, "Featured" %>
    <%= form.check_box :featured %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<% @title = "Artists | Loud House Publishing" %>
<p id="notice"><%= notice %></p>

<h1>Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.description %></td>
        <td><%= image_tag artist.photo.url(:thumb) %></td>
        <td><%= artist.featured %></td>
        <td><%= link_to 'Show', artist %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
          <td><%= link_to 'Delete', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Artist', new_artist_path %>
<% end %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<% @title = @artist.name + " | Loud House Publishing" %>
<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @artist.description %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @artist.photo.url(:home) %>
</p>

<p>
  <strong>Featured?:</strong>
  <%= @artist.featured %>
</p>

<%= link_to 'Back', artists_path %>
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_artist_path(@artist) %>
  <%= link_to 'Delete', @artist, method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>