config/routes.rb
Rails.application.routes.draw do
  resources :images, only: [:create, :destroy]
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :releases
  resources :artists
  resources :events
  resources :studio, only: [:index]
  resources :about, only: [:index]
  resources :contact, only: [:index]

  post 'contact', to: 'contact#new'

  root to: "home#index"
end

app/models/event.rb
class Event < ApplicationRecord
  has_attached_file :photo,
                    :styles => { :home => "500x500" },
                    :s3_protocol => 'https',
                    :s3_host_name => ENV['S3_HOST_NAME'],
                    :path => ENV['S3_PATH_EVENTS'],
                    :storage => 's3',
                    :s3_region => ENV['AWS_REGION'],
                    :bucket => ENV['S3_BUCKET_NAME']

  #TODO set default "missing" image to loudhouse logo
  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all.sort_by(&:date)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:headliner, :supporting, :price, :address, :city, :zip, :state, :date, :time, :description, :photo)
    end
end

app/views/events/_form.html.erb
<%= form_for @event, :html => { :multipart => true } do |form| %>
  <div class="col-md-12">
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :headliner %>
      <%= form.text_field :headliner %>
    </div>

    <div class="field">
      <%= form.label :supporting %>
      <%= form.text_field :supporting %>
    </div>

    <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price %>
    </div>

    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address %>
    </div>

    <div class="field">
      <%= form.label :photo, "Photo" %>
      <%= form.file_field :photo %>
    </div>

    <div class="field">
      <%= form.label :city %>
      <%= form.text_field :city %>
    </div>

    <div class="field">
      <%= form.label :zip %>
      <%= form.text_field :zip %>
    </div>

    <div class="field">
      <%= form.label :state %>
      <%= form.text_field :state %>
    </div>

    <div class="field">
      <%= form.label :date %>
      <%= form.date_select :date %>
    </div>

    <div class="field">
      <%= form.label :time %>
      <%= form.time_select :time, {minute_step: 15, ampm: true} %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, class: "description" %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% @title = "Events | Loud House Publishing" %>
<p id="notice"><%= notice %></p>
<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Headliner</th>
      <th>Supporting</th>
      <th>Price</th>
      <th>Address</th>
      <th>City</th>
      <th>Zip</th>
      <th>State</th>
      <th>Date</th>
      <th>Show</th>
      <th>Description</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<!--  TODO should probably add in some helpers to dry this out-->
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.headliner %></td>
        <td><%= event.supporting %></td>
        <td><%= event.price %></td>
        <td><%= event.address %></td>
        <td><%= event.city %></td>
        <td><%= event.zip %></td>
        <td><%= event.state %></td>
        <td><%= event.date %></td>
        <td><%= event.time %></td>
        <td><%= event.description %></td>
        <td><%= image_tag event.photo.url(:thumb) %></td>
        <td><%= link_to 'Show', event %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Event', new_event_path %>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<% @title = @event.headliner + " | Loud House Publishing" %>
<p>
  <strong>Headliner:</strong>
  <%= @event.headliner %>
</p>

<p>
  <strong>Supporting:</strong>
  <%= @event.supporting %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.price %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @event.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @event.zip %>
</p>

<p>
  <strong>State:</strong>
  <%= @event.state %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @event.photo.url(:home) %>
</p>

<%= link_to 'Back', events_path %>
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_event_path(@event) %>
  <%= link_to 'Delete', @event, method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>