config/routes.rb
Rails.application.routes.draw do
  resources :images, only: [:create, :destroy]
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :releases
  resources :artists
  resources :events
  resources :studio, only: [:index]
  resources :about, only: [:index]
  resources :contact, only: [:index]

  post 'contact', to: 'contact#new'

  root to: "home#index"
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end

  def new
    ApplicationMailer.contact_email(contact_params).deliver
    ApplicationMailer.contact_confirm(contact_params).deliver
    flash[:notice] = "Thank you for contacting the Loud House. We will get back to you as soon as possible."
    redirect_to(root_path)
  end

  def contact_params
    params.permit(:name, :email, :subject, :message)
  end
end

app/views/contact/index.html.erb
<% @title = "Contact Us" %>
<div class="static-page" id="contact">
  <div class="col-md-7 static-page-body" id="contact">
    <h1 class="header" id="contact">Contact Us</h1>

    <hr id="contact">

    <p class="static-page-text" id="contact">
      Questions? Send us at email at loudhousepublishing@gmail.com or give us a call at (831) 555-5555
    </p>
    <div class="col-md-6 offset-md-3 contact-form">
      <%= form_with(url: contact_path, method: :post) do |f| %>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control", placeholder: "Name", required: true %>
        </div>
        <div class="form-group">
          <%= f.text_field :email, class: "form-control", placeholder: "Email", required: true %>
        </div>
        <div class="form-group">
          <%= f.text_field :subject, class: "form-control", placeholder: "Subject", required: true  %>
        </div>
        <div class="form-group">
          <%= f.text_area :message, rows: 10, class: "form-control", placeholder: "Message", required: true  %>
        </div>
        <div class="form-group">
          <%= f.submit "Submit", class: 'btn btn-primary',  id: 'label' %>
        </div>
      <% end %>
    </div>
  </div>
</div>