config/routes.rb
Rails.application.routes.draw do
  resources :images, only: [:create, :destroy]
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :releases
  resources :artists
  resources :events
  resources :studio, only: [:index]
  resources :about, only: [:index]
  resources :contact, only: [:index]

  post 'contact', to: 'contact#new'

  root to: "home#index"
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  before_action :set_release, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /releases
  # GET /releases.json
  def index
    @releases = Release.all.sort_by(&:release).reverse
  end

  # GET /releases/1
  # GET /releases/1.json
  def show
  end

  # GET /releases/new
  def new
    @release = Release.new
    @artists = Artist.all
  end

  # GET /releases/1/edit
  def edit
    @artists = Artist.all
  end

  # POST /releases
  # POST /releases.json
  def create
    @release = Release.new(release_params)

    respond_to do |format|
      if @release.save
        format.html { redirect_to @release, notice: 'Release was successfully created.' }
        format.json { render :show, status: :created, location: @release }
      else
        format.html { render :new }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /releases/1
  # PATCH/PUT /releases/1.json
  def update
    respond_to do |format|
      if @release.update(release_params)
        format.html { redirect_to @release, notice: 'Release was successfully updated.' }
        format.json { render :show, status: :ok, location: @release }
      else
        format.html { render :edit }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /releases/1
  # DELETE /releases/1.json
  def destroy
    @release.destroy
    respond_to do |format|
      format.html { redirect_to releases_url, notice: 'Release was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_release
    @release = Release.find(params[:id])
  end

  def release_params
    params[:release][:artist] = Artist.find(params[:release][:artist_id]).name
    params.require(:release).permit(:artist_id, :title, :release, :description, :album_art, artist_attributes: [:name, :description, :photo, :featured])
  end
end

app/views/releases/_form.html.erb
<%= form_with(model: release, local: true) do |form| %>
  <% if release.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(release.errors.count, "error") %> prohibited this release from being saved:</h2>

      <ul>
      <% release.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :artist_id, "Artist" %>
    <%= form.collection_select :artist_id, @artists, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :release %>
    <%= form.date_select :release %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "description" %>
  </div>

  <div class="field">
    <%= form.label :album_art, "Album Art" %>
    <%= form.file_field :album_art %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/releases/edit.html.erb
<h1>Editing Release</h1>

<%= render 'form', release: @release %>

<%= link_to 'Show', @release %> |
<%= link_to 'Back', releases_path %>

app/views/releases/index.html.erb
<% @title = "Releases | Loud House Publishing" %>
<p id="notice"><%= notice %></p>

<h1>Releases</h1>

<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Title</th>
      <th>Release</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @releases.each do |release| %>
      <tr>
        <% if release.artist %>
          <td><%= release.artist.name %></td>
        <% end %>
        <td><%= release.title %></td>
        <td><%= release.release %></td>
        <td><%= release.description %></td>
        <td><%= image_tag release.album_art.url(:thumb) %></td>
        <td><%= link_to 'Show', release %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_release_path(release) %></td>
          <td><%= link_to 'Delete', release, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Release', new_release_path %>
<% end %>

app/views/releases/new.html.erb
<h1>New Release</h1>

<%= render 'form', release: @release %>

<%= link_to 'Back', releases_path %>

app/views/releases/show.html.erb
<% @title = @release.title + " | Loud House Publishing" %>
<p>
  <strong>Artist:</strong>
  <% if @release.artist %>
    <%= @release.artist.name %>
  <% end %>
</p>

<p>
  <strong>Title:</strong>
  <%= @release.title %>
</p>

<p>
  <strong>Release:</strong>
  <%= @release.release %>
</p>

<p>
  <strong>Description:</strong>
  <%= @release.description %>
</p>

<p>
  <strong>Album Art:</strong>
  <%= image_tag @release.album_art.url(:thumb) %>
</p>

<%= link_to 'Back', releases_path %>
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_release_path(@release) %>
  <%= link_to 'Delete', @release, method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>